export { default as ErrorPage } from './error/error.vue'
export { default as IncidentPage } from './incident/incident.vue'
export { default as IncidentsPage } from './incidents/incidents.vue'
export { default as IndexPage } from './index/index.vue'
export { default as RootPage } from './root/root.vue'
export { default as AnalyticsPage } from './analytics/analytics.vue'
