name: 'CD'
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:

  prepare:
    name: 'Prepare'
    uses: rfcx/cicd/.github/workflows/notify-prepare.yaml@master
    with:
      repo: guardian-dashboard
      workflow-id: cd.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  configure:
    name: 'Configure'
    runs-on: ubuntu-latest
    needs: [prepare]
    outputs:
      namespace: ${{ steps.configuration.outputs.namespace }}
    steps:
      - name: 'Conditional environment'
        id: configuration
        run: |
          if [[ "${{ needs.prepare.outputs.branch-name }}" == "master" ]]; then
            echo "::set-output name=namespace::production"
          elif [[ "${{ needs.prepare.outputs.branch-name }}" == "staging" ]]; then
            echo "::set-output name=namespace::staging"
          else
            echo "::set-output name=namespace::testing"
          fi

  deploy-rfcx-local:
    name: 'Deploy: rfcx-local'
    needs: [prepare, configure]
    if: ${{ needs.configure.outputs.namespace == 'production' }}
    uses: rfcx/cicd/.github/workflows/rfcx-local-cd.yaml@master
    with:
      repo: guardian-dashboard
      dockerfile: build/Dockerfile
      targets: '["guardian-dashboard"]'
      deployments: |
        [
          {"name": "guardian-dashboard", "image": "guardian-dashboard"}
        ]


  notify:
    name: 'Notify'
    if: ${{ always() }}
    needs: [prepare, deploy-rfcx-local]
    uses: rfcx/cicd/.github/workflows/notify-send.yaml@master
    with:
      repo: guardian-dashboard
      branch-name: ${{ needs.prepare.outputs.branch-name }}
      workflow-id: cd.yaml
      previous-run-id: ${{ needs.prepare.outputs.previous-run-id }}
      status: ${{ needs.deploy-rfcx-local.result }}
      always: true
      notification-title: 'CD: Guardian Dashboard'
      notification-footer: "Deploy (rfcx-local): ${{ needs.deploy-rfcx-local.result || 'n/a' }}"
      notification-success-statement: '{0} deployed the build!'
    secrets:
      slack-webhook: ${{ secrets.SLACK_ALERT_COREDT_WEBHOOK }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
    